cd C:\WINdows\system32\inetsrv

appcmd add vdir /app.name:"SeoSiteClusterSSL adt"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL airforce"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL arthur"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL asmnet"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL bidmc"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL C3"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL carnival"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL choc"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL chrobinson"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL citi"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL citibank"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL disneychinaenglish"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL ea"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL ebay"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL emploisypg"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL equinox"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL espn"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL Experian"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL FloridaBlue"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL grainger"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL gwinnett"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL highpoint"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL interiorhealth"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL jobsypg"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL lifetech"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL loram"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL masonicare"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL Mcdonalds"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL medtronic"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL memorialcare"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL memorialcarelongbeach"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL memorialcaremillers"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL memorialcareorangecoast"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL memorialcaresaddleback"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL MissionHealth"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL monsanto"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL multicare"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL nestle"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL Novant"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL officedepot"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL ohiohealth"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL owenscorning"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL pacificdental"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL pg"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL phsa"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL regeneron"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL rgp"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL select"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL sharp"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL suncoast"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL tenet"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL test"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL texaschildrens"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL tmp"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL vhs"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
appcmd add vdir /app.name:"SeoSiteClusterSSL wakemed"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile
Appcmd add vdir /app.name:"SeoSiteClusterSSL walmart"/ /path:/m /physicalPath:D:\p4\Deployment.TMPPRODCLUSTER\AdCommsNA\dev\Product\TalentBrew\TB4.0\web\SeoSiteMobile