cd "c:\Program Files (x86)\IIS\Microsoft Web Deploy V3"

msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS03 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS03.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS04 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS04.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS05 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS05.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS06 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS06.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS07 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS07.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS08 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS08.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS09 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS09.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS10 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS10.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS11 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS11.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS12 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS12.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS13 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS13.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS14 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS14.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS15 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS15.log
msdeploy -verb:sync -source:apphostconfig="PX" -dest:apphostconfig="PX",computername=HBEUPXBCS16 -disablelink:contentextension -disablelink:FrameworkConfigExtension -disablelink:CertificateExtension -disablelink:AppPoolExtension -disablelink:HttpCertConfigExtension > C:\Webdeploylogs\PX\Prod\HBEUPXBCS16.log
